name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  validate-version:
    name: Validate version format
    runs-on: ubuntu-24.04
    steps:
      - name: Validate semver format
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if ! [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $TAG_NAME. Version must follow semver format (e.g., 1.2.3) without any prefix."
            echo "::error::Please use the format: MAJOR.MINOR.PATCH (e.g., 0.1.0, 1.0.0, 2.3.4)"
            exit 1
          fi
          echo "Version format is valid: $TAG_NAME"

  build-and-publish:
    name: Build and publish to PyPI
    needs: validate-version
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/caylent-devcontainer-cli
    permissions:
      id-token: write  # Required for PyPI trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies for Python build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev
          sudo apt-get install -y libbz2-dev libreadline-dev libsqlite3-dev curl
          sudo apt-get install -y libncursesw5-dev xz-utils tk-dev libxml2-dev
          sudo apt-get install -y libxmlsec1-dev libffi-dev liblzma-dev bc

      - name: Install ASDF
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0
          echo "$HOME/.asdf/bin" >> $GITHUB_PATH
          echo "$HOME/.asdf/shims" >> $GITHUB_PATH
          source $HOME/.asdf/asdf.sh

      - name: Install ASDF plugins and tools
        run: |
          cat .tool-versions | cut -d' ' -f1 | xargs -I{} asdf plugin add {} || true
          asdf install
          asdf reshim

      - name: Install build dependencies
        run: |
          cd $GITHUB_WORKSPACE/caylent-devcontainer-cli
          pip install --upgrade pip
          make install
          asdf reshim

      - name: Update version in package files
        run: |
          TAG_VERSION="${{ github.ref_name }}"
          cd $GITHUB_WORKSPACE/caylent-devcontainer-cli

          # Update version in __init__.py
          if [ -f "src/caylent_devcontainer_cli/__init__.py" ]; then
            sed -i "s/__version__ = .*/__version__ = \"$TAG_VERSION\"/" src/caylent_devcontainer_cli/__init__.py
          fi

          # Update version in pyproject.toml if it exists
          if [ -f "pyproject.toml" ]; then
            sed -i "s/version = .*/version = \"$TAG_VERSION\"/" pyproject.toml
          fi

          # Update version in setup.py if it exists
          if [ -f "setup.py" ]; then
            sed -i "s/version=['\"][^'\"]*['\"]/version=\"$TAG_VERSION\"/" setup.py
          fi

          echo "Updated package version to $TAG_VERSION"

      - name: Build package
        run: |
          cd $GITHUB_WORKSPACE/caylent-devcontainer-cli
          make publish

      - name: Publish to PyPI
        id: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: caylent-devcontainer-cli/dist/
          skip_existing: true
          attestations: false

      - name: Send success notification to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ PyPI Publish Successful",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ PyPI Publish Successful"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Version ${{ github.ref_name }} has been successfully published to PyPI.\n\n<https://pypi.org/p/caylent-devcontainer-cli|View on PyPI> | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send failure notification to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ PyPI Publish Failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ PyPI Publish Failed"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Failed to publish version ${{ github.ref_name }} to PyPI.\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View error details>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
