name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  validate-version:
    name: Validate version format
    runs-on: ubuntu-24.04
    steps:
      - name: Validate semver format
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if ! [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format: $TAG_NAME. Version must follow semver format (e.g., 1.2.3) without any prefix."
            echo "::error::Please use the format: MAJOR.MINOR.PATCH (e.g., 0.1.0, 1.0.0, 2.3.4)"
            exit 1
          fi
          echo "Version format is valid: $TAG_NAME"

  build-and-publish:
    name: Build and publish to PyPI
    needs: validate-version
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/caylent-devcontainer-cli
    permissions:
      id-token: write  # Required for PyPI trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ASDF
        uses: asdf-vm/actions/setup@v3

      - name: Install ASDF plugins and tools
        run: |
          cat .tool-versions | cut -d' ' -f1 | xargs -I{} asdf plugin add {} || true
          asdf install
          asdf reshim

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          cd caylent-devcontainer-cli
          make build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: caylent-devcontainer-cli/dist/
          